### ISSUE TITLE
Gateway connects with a different client id each time

### ISSUE THREAD

**Issue by muniter** [openlumi/lumimqtt#13]
Hello just installed, The functionality is great. But as the title says every time the gateway connects to the mqtt broker It does so with a different client id.

Last four reboots. Creates the following devices in Home Assistant MQTT integration.
```
xiaomi_gateway_0x116a18881e53
xiaomi_gateway_0x212617c4e71a
xiaomi_gateway_0x63e75752b847
xiaomi_gateway_0xc46e7b7df285
xiaomi_gateway_0xef23022fc624
```

Current configuration `/etc/lumimqtt.json`

```
{
    "mqtt_host": "10.3.30.15",
    "mqtt_port": 1883,
    "mqtt_user": "user",
    "mqtt_password": "password",
    "topic_root": "lumi/main-room-gateway",
    "sensor_retain": false,
    "sensor_threshold": 50,
    "sensor_debounce_period": 60
}
```
EDIT:

I can see in the code the use of `uuid.get_node` to obtain the device mac address.

https://github.com/openlumi/lumimqtt/blob/22317aba7fd129339ffacce85bafcfc75b654c8d/lumimqtt/__main__.py#L5
https://github.com/openlumi/lumimqtt/blob/22317aba7fd129339ffacce85bafcfc75b654c8d/lumimqtt/__main__.py#L43

And according to the [documentation](https://docs.python.org/3/library/uuid.html#uuid.getnode) if it can't get the MAC address It will use a random number, therefore in every reboot we are getting a different "client" and a "new" device being connected to the mqtt broker. Maybe a better idea would be using the wlan mac provided by ddwrt.

Or even easier let the user just set the client id. And let's make clear It should be unique in their mqtt network.

**Comment by devbis** [comment]
What is the reason  that your gateway cannot get mac of the device?
What hardware do you use and what openwrt version?

**Comment by muniter** [comment]
No idea why It can't obtain the MAC address, but I imagine It can't since it's behaving randomly, as the python documentation states It would If It can't get the MAC.

I'm running OpenWrt 19.07.6 on a DGNWG05LM.

**Comment by ha0y** [comment]
The same issue here. Running OpenWrt 19.07.6 on a ZHWG11LM

**Comment by definitio** [comment]
Can confirm. I have duplicates in HA with different ids.

**Comment by devbis** [comment]
Can you all please confirm that you have other interfaces that lo, wlan0, wlan1? Like usb0.
The output of `ip addr` would help. 
Anyway, the new version 1.0.11 uses a fixed interface for the mac address source and allows setting custom device_id in the config. (thanks to @muniter ) Try it.

**Comment by muniter** [comment]
Hello @devbis I don't have any additional interface.

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether c4:6e:7b:7d:f2:85 brd ff:ff:ff:ff:ff:ff
    inet 10.3.30.130/24 brd 10.3.30.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::c66e:7bff:fe7d:f285/64 scope link
       valid_lft forever preferred_lft forever
3: wlan1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether c6:6e:7b:7d:f2:85 brd ff:ff:ff:ff:ff:ff

```

**Comment by devbis** [comment]
That's strange. Don't have an idea why it uses random mac instead of the wlan0's.
Anyway, I added force picking mac address from `wlan0` interface in the latest version, so I'm closing the task for now.
