### ISSUE TITLE
ERROR:lumimqtt.lumimqtt:Connection lost. Will retry in 10 seconds

### ISSUE THREAD

**Issue by ha0y** [openlumi/lumimqtt#17]
Hello,
I've hacked my gateway and installed lumimqtt following the readme of ``openlumi`` and ``lumimqtt``. My ``/etc/lumimqtt.json`` like this: 
```json
{
    "mqtt_host": "192.168.0.101",
    "mqtt_port": 1883,
    "mqtt_user": "hass",
    "mqtt_password": "xxxxxx",
    "topic_root": "lumi/{MAC}",
    "sensor_retain": true,
}
```
and when I run ``lumimqtt``
```
INFO:lumimqtt.__main__:Start lumimqtt 1.0.10
ERROR:lumimqtt.lumimqtt:Connection lost. Will retry in 10 seconds
```
It just kept showing the ERROR.

I am sure the mqtt host can be reached by pinging it in OpenWrt. All other devices can connect to this server.

What could be the reason? Thanks in advance!

**Comment by ha0y** [comment]
Oh my!
The cause is the last comma in json! After removing it works well.

But WHY the error message is ``Connection lost`` ???

**Comment by devbis** [comment]
If the config is incorrect it used a default connection to the localhost.

Fixed in https://github.com/openlumi/lumimqtt/commit/48294aba443dd4df4174008da3d903bfc0001cd6
It will raise an exception if JSON is invalid
