### ISSUE TITLE
lumimqtt with homebridge

### ISSUE THREAD

**Issue by 4ban** [openlumi/lumimqtt#26]
Hey, I do have a pretty default installation of the OpenWRT + zigbee2mqtt + lumimqtt
And I was able to connect the remote homebridge to the MQTT broker that runs on the gateway. 

I can see all Zigbee devices connected to it but I can't get the gateway itself (LED control, light sensor, audio and so on). 

Should I configure gateway lumimqtt somehow or use a specific homebridge plugin to get access to the gateway led and speaker? 

Thanks

**Comment by devbis** [comment]
Topics for gateway devices are located under `lumi/0xMACADDRESS/` prefix. Auto-dicscovery topics are provided for Home Assistant only, I have no idea how devices are configured in Homebridge. Maybe the ways to add topics from MQTT to you smart home instance are described in the HB documentation.
