### ISSUE TITLE
No such file or directory: '/dev/input/event0'

### ISSUE THREAD

**Issue by syssi** [openlumi/lumimqtt#29]
I've installed lumimqtt on a OpenLumi gateway (ZHWG11LM):

```
$ pip3 install -U lumimqtt
Collecting lumimqtt
  Downloading lumimqtt-1.0.14-py3-none-any.whl (27 kB)
Collecting aio-mqtt>=0.2.0
  Downloading aio_mqtt-0.2.0-py3-none-any.whl (18 kB)
Requirement already satisfied: evdev>=1.0.0 in /usr/lib/python3.9/site-packages (from lumimqtt) (1.4.0)
Installing collected packages: aio-mqtt, lumimqtt
Successfully installed aio-mqtt-0.2.0 lumimqtt-1.0.14
```

If I try to start the daemon the startup aborts with the following error:

```
$ lumimqtt
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/evdev/device.py", line 126, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/lumimqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/lumimqtt/__main__.py", line 80, in main
    for device in devices(
  File "/usr/lib/python3.9/site-packages/lumimqtt/platform.py", line 92, in devices
    return sensors(binary_sensors) + buttons() + lights() + \
  File "/usr/lib/python3.9/site-packages/lumimqtt/platform.py", line 44, in buttons
    buttons_.append(Button(name=name,
  File "/usr/lib/python3.9/site-packages/lumimqtt/button.py", line 41, in __init__
    self.ev_device = InputDevice(self.device_file)
  File "/usr/lib/python3.9/site-packages/evdev/device.py", line 128, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event0'
```

Do I need to load a kernel module manually to have `/dev/input/event0` available? Did I miss something?

Kind regards,

Sebastian

**Comment by devbis** [comment]
Usually, everything is compiled and no need for extra configuring.
What firmware do you use?

**Comment by syssi** [comment]
The stock firmware was 3.0.3_004 before installing openlumi.

**Comment by devbis** [comment]
And what version of OpenWrt is installed? It is written on the first page on web interface

**Comment by syssi** [comment]
Powered by LuCI openwrt-21.02 branch (git-21.231.26241-422c175) / OpenLumi 21.02.0 r16279-5cc0535800

I did install OpenWRT via the Openlumi install.sh. I was unsure the rootfs, kernel and bootloader is replaced completly by OpenWRT or are there leftovers to the stock firmware version could be important.

**Comment by devbis** [comment]
Upgrade your firmware with the latest sysupgrade.bin from https://openlumi.github.io/releases/21.02.1/targets/imx6/generic/
for your device. openlumi-21.02.1-imx6-aqara_zhwg11lm-squashfs-sysupgrade.bin is for your gateway.
You can do it via web UI in a common way : https://openwrt.org/docs/guide-quick-start/sysupgrade.luci

**Comment by syssi** [comment]
Thanks for your support! I will give it a try later the day!

**Comment by syssi** [comment]
The update solved the issue! Thanks!!
