### ISSUE TITLE
Luminance sensor reading too low

### ISSUE THREAD

**Issue by blackie333** [openlumi/lumimqtt#30]
Hello,
First of all - thank you for this project, I have a lot of fun with it.
I'm very happy overall, but run across a problem with my DGNWG05LM gateway luminance sensor readings.
I have another Aquara gateway(DGNWG02LM+original fw) in the same room and the sensor readings differ too much.
OpenLumi lux values are very low compared with the other aquara values(up to 1500 lux), please see the pictures.
Morning: ![image](https://user-images.githubusercontent.com/22171229/159856272-61fd4f1b-d1c4-4ba7-8450-e2be90283315.png)
Afternoon: ![image](https://user-images.githubusercontent.com/22171229/159921557-0936c748-054a-42e9-bf74-ff371e1b8aa7.png)

Seems like in the morning multiplying the value with factor 15 could make them equal.
With more sunshine the factor is decreasing. Can you please check where the problem could be? 
Is there a way to calibrate the sensor or adjust the values ?
Thank you in advance

**Comment by devbis** [comment]
It was calibrated to another light sensor and uses 0.25 value as a coefficient to calibrate. For other installations, it is precise enough and it could happen that your Aqara sensor provides incorrect values. In case you want to adjust it to your sensor, you could change the value in your installed files at the gateway. https://github.com/openlumi/lumimqtt/blob/main/lumimqtt/sensors.py#L49
