### ISSUE TITLE
how to connect xiaomi gateway DGNWG05LM with hassio via MQTT

### ISSUE THREAD

**Issue by ghost** [openlumi/lumimqtt#5]
Hi,
Mike here from Italy.
I have the Xiaomi Gateway DGNWG05LM and I have hacked it with your guide and repositories:
xiaomi-gateway-openwrt
zigbee2mqtt
lumimqtt

I am not that expert in this type of communication so I am stucking in how to make my hassio communicating with the gateway.
Can you please help me in the next steps?

best regards and thanks
mike

**Comment by devbis** [comment]
Hey @Mike-computing 

You have to use MQTT server to handle events and manage devices. Both zigbee2mqtt and lumimqtt support Homeassistant mqtt autodiscovery, so you may use the MQTT integration in HA and all devices will be attached automatically. 
You can use mosquito server on the gateway or on external device, e.g. raspberrypi with homeassistant installed.

You will be able to manage zigbee sensors and the gateway peripheral like light sensor and LED lights.

**Comment by Mike-computing** [comment]
It works now but I am not able to use the gateway light sensor or LED.
Any suggestions?

Thanks again

**Comment by devbis** [comment]
lumimqtt is the application that allows using less and light sensor by default. Do you use MQTT integration in HASS?


Here is the device with 3 entities that appears by default:

![изображение](https://user-images.githubusercontent.com/12081127/104312190-5549a380-54e7-11eb-85a2-35b29199a041.png)

**Comment by koraysels** [comment]
I have the same prblem.. I have everything setup and configured.. My zogbee sensors get picked up by HA but the gateway itself doesn't. Normally lumimqtt is for the gateway itself to get picked up right ? and it can run alongside zigbee2mqtt right?
