### ISSUE TITLE
offline status after reboot

### ISSUE THREAD

**Issue by acidquest** [openlumi/lumimqtt#9]
После перезагрузки хаба всегда статус в mqtt - offline. Пока не зайду с помощью mqtt explorer и не поменяю статус вручную на online ни свет, ни кнопка, ни датчик света не работают. Можно при запуске lumimqtt сделать установку статуса. Спасибо

**Comment by definitio** [comment]
Вообще при подключении статус `online` отправляется. Однако у меня тоже периодически эта проблема возникает, но далеко не каждый раз, так что непонятно с чем это связано.

**Comment by acidquest** [comment]
Спасибо, понял. Буду тогда с помощью mosquito_pub при загрузке статус принудительно менять

**Comment by definitio** [comment]
Может пока откроете? Проблема всё-таки есть, пусть висит здесь, чтобы про неё помнили.

**Comment by acidquest** [comment]
Ok

**Comment by definitio** [comment]
@acidquest у меня проблема больше не воспроизводится, проверьте у себя.

**Comment by acidquest** [comment]
спасибо, только дошли руки обновить. пока все хорошо, проблемы нет. если появится, то открою заново, пока что закрываю. еще раз спасибо за компонент
